// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLRapChieuPhim.Infrastructure.Entity_Framework_Core;

#nullable disable

namespace QLRapChieuPhim.Migrations
{
    [DbContext(typeof(QLRapChieuPhimDbContext))]
    partial class QLRapChieuPhimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLRapChieuPhim.Entities.CumRap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenCum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CumRaps");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.KeHoach", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaCum")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaPhim")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KeHoachs");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.LichChieu", b =>
                {
                    b.Property<string>("PhimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RapId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChuoiMaSuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("PhimId", "RapId");

                    b.ToTable("LichChieus");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.Phim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CoLa3D")
                        .HasColumnType("bit");

                    b.Property<bool>("CoLongTieng")
                        .HasColumnType("bit");

                    b.Property<string>("MaTheLoaiChinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Phims");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.PhimTheLoaiPhu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("PhimTheLoaiPhus");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.Rap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCum")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("TongGhe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Raps");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.SuatChieu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GioBatDau")
                        .HasColumnType("int");

                    b.Property<int>("PhutBatDau")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suats");
                });

            modelBuilder.Entity("QLRapChieuPhim.Entities.TheLoai", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TheLoais");
                });
#pragma warning restore 612, 618
        }
    }
}
